version: "3"
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: proxy
    depends_on:
      - backend
      - frontend
      - backoffice
    networks:
      - backend
  backend:
    image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/<your-repository-name>:<your-tag>
    ports:
      - "8080:8080"
    restart: always
    # networks:
    #   - api
  frontend:
    image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/<your-repository-name>:<your-tag>
    ports:
      - "3000:3000"
    restart: always
    # networks:
    #   - api
  backoffice:
    image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/<your-repository-name>:<your-tag>
    ports:
      - "3001:3001"
    restart: always
    # networks:
    #   - api
  mariadb:
    image: mariadb:10
    environment:
      MARIADB_DATABASE: "<MARIADB_DATABASE>"
      MARIADB_USER: "<MARIADB_USER>"
      MARIADB_PASSWORD: "<MARIADB_PASSWORD>"
      MARIADB_ROOT_PASSWORD: "<MARIADB_ROOT_PASSWORD>"
    ports:
      - 3306:3306
    volumes:
      - "./mariadb/data:/var/lib/mysql"
    restart: always
    container_name: mariadb
    # networks:
    #   - api
# networks:
# api:
# driver: bridge
